#!/bin/bash

######################################################################
#
# Put this file in your gitolite-admin;
# /home/user/gitolite-admin/local/hooks/repo-specific/deployweb
#
while read oldrev newrev refname
do
    BRANCH=$(git rev-parse --symbolic --abbrev-ref $refname)
    echo "Commit was for branch $BRANCH"

    if [[ "$BRANCH" == "master" ]];then

        # Get project name from current directory (without .git)
        PROJECT=$(basename "$PWD")
        PROJECT=${PROJECT%.git}

        echo "Project $PROJECT added to deploy list."
        echo $PWD > /srv/git/deploy/$PROJECT
    fi

done
