#!/bin/sh
#
# /etc/rc.d/fetchmail: start/stop fetchmail daemon
#

SSD=/sbin/start-stop-daemon
PROG=/usr/bin/fetchmail
PID=/var/run/fetchmail/fetchmail.pid
IDS=/var/lib/fetchmail/.fetchids
PUID=45
PGID=100
OPTS="-f /etc/fetchmailrc -i $IDS --pidfile $PID"

case $1 in
start)
        $SSD --chuid $PUID:$PGID --user $PUID --exec $PROG --start -- $OPTS
        ;;
stop)
        $SSD --stop --remove-pidfile --retry 10 --pidfile $PID
        ;;
restart)
        $0 stop
        $0 start
        ;;
reload)
        $SSD --stop --signal HUP --pidfile $PID
        ;;
status)
        $SSD --status --pidfile $PID
        case $? in
        0) echo "$PROG is running with pid $(head -1 $PID)" ;;
        1) echo "$PROG is not running but the pid file $PID exists" ;;
        3) echo "$PROG is not running" ;;
        4) echo "Unable to determine the program status" ;;
        esac
        ;;
*)
        echo "usage: $0 [start|stop|restart|reload|status]"
        ;;
esac
# End of file
